---
openapi: 3.0.1
info:
  title: API V1
  version: v1
paths:
  "/api/v1/auth/register":
    post:
      summary: User Registration
      tags:
      - Authentication
      parameters: []
      responses:
        '200':
          description: User registered successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: Signed up successfully. Please confirm your email.
        '422':
          description: User registration failed
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: You must have a valid Tito ticket to register.
                  errors:
                    type: array
                    items:
                      type: string
                    example: []
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                  example: user@example.com
                password:
                  type: string
                  example: password123
                password_confirmation:
                  type: string
                  example: password123
              required:
              - email
              - password
              - password_confirmation
  "/api/v1/auth/login":
    post:
      summary: User Login
      tags:
      - Authentication
      parameters: []
      responses:
        '200':
          description: User logged in successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: Logged in successfully
                  data:
                    type: object
                    properties:
                      token:
                        type: string
                        example: eyJhbGciOiJIUzI1...
                      user:
                        type: object
                        properties:
                          id:
                            type: integer
                            example: 1
                          email:
                            type: string
                            example: user@example.com
        '401':
          description: Invalid credentials
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: Invalid email or password
                  errors:
                    type: array
                    items:
                      type: string
                    nullable: true
      requestBody:
        content:
          application/json:
            schema:
              type: object
              required:
              - email
              - password
              properties:
                email:
                  type: string
                  example: user@example.com
                password:
                  type: string
                  example: password123
  "/api/v1/auth/logout":
    delete:
      summary: User Logout
      tags:
      - Authentication
      responses:
        '200':
          description: User logged out successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: Logged out successfully
                  data:
                    type: object
                    nullable: true
servers:
- url: http://localhost:3000
