---
openapi: 3.0.1
info:
  title: API V1
  version: v1
paths:
  "/api/v1/auth/register":
    post:
      summary: User Registration
      tags:
      - Authentication
      parameters: []
      responses:
        '200':
          description: User registered successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: Signed up successfully. Please confirm your email.
        '422':
          description: User registration failed
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: You must have a valid Tito ticket to register.
                  errors:
                    type: array
                    items:
                      type: string
                    example: []
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                  example: user@example.com
                password:
                  type: string
                  example: password123
                password_confirmation:
                  type: string
                  example: password123
              required:
              - email
              - password
              - password_confirmation
servers:
- url: http://localhost:3000
